import type { Manifest } from "./types.js";

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * A valid TS type name from an arbitrary collection name: non-identifier chars (e.g. the hyphens in
 * a filename-derived `default-cards-2026`) become `_`, and a leading digit gets an `_` prefix.
 */
function typeNameFor(name: string): string {
  const safe = name.replace(/[^A-Za-z0-9_$]/g, "_").replace(/^([0-9])/, "_$1") || "_";
  return safe[0]!.toUpperCase() + safe.slice(1);
}

/** An object/interface key: emitted bare when it's a valid identifier, otherwise quoted (`"a-b": …`). */
function propKey(name: string): string {
  return IDENTIFIER_RE.test(name) ? name : JSON.stringify(name);
}

function tsTypeForKind(kind: string): string {
  switch (kind) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "string":
    case "date":
      return "string";
    case "json":
    default:
      return "unknown";
  }
}

function generatedHeader(generatorVersion: string): string {
  return `// generated by static-shard@${generatorVersion} — do not edit`;
}

export function generateSchemaTs(manifest: Manifest, generatorVersion: string): string {
  const { collection, fields } = manifest.schema;
  const typeName = typeNameFor(collection);
  const collectionKey = propKey(collection);
  const fieldEntries = Object.entries(fields);

  const interfaceLines = fieldEntries
    .map(([name, field]) => {
      const tsType = field.multi ? `${tsTypeForKind(field.kind)}[]` : tsTypeForKind(field.kind);
      // Payload-only "json" fields are opaque and their presence isn't tracked — always optional.
      const optional = field.absent || field.kind === "json" ? "?" : "";
      return `  ${propKey(name)}${optional}: ${tsType};`;
    })
    .join("\n");

  const indexedFieldLines = fieldEntries
    .filter(([, field]) => field.indexed)
    .map(([name, field]) => {
      const operators = field.operators.map((op) => `"${op}"`).join(", ");
      const multi = field.multi ? ", multi: true" : "";
      const absent = field.absent ? ", absent: true" : "";
      const pk = field.pk ? ", pk: true" : "";
      return `      ${propKey(name)}: { kind: "${field.kind}", operators: [${operators}]${multi}${absent}${pk} },`;
    })
    .join("\n");

  const pkLine = manifest.schema.pk !== undefined ? `    pk: ${JSON.stringify(manifest.schema.pk)},\n` : "";

  return `${generatedHeader(generatorVersion)}
export interface ${typeName} {
${interfaceLines}
}

export interface Records {
  ${collectionKey}: ${typeName};
}

export const schema = {
  ${collectionKey}: {
${pkLine}    fields: {
${indexedFieldLines}
    },
  },
} as const;

export type Schema = typeof schema;
`;
}

export function generateClientTs(manifest: Manifest, opts: { basePath: string; generatorVersion: string }): string {
  const { collection } = manifest.schema;
  const collectionKey = propKey(collection);
  const collectionIndex = JSON.stringify(collection);

  return `${generatedHeader(opts.generatorVersion)}
import { createClient, type Collection, type ClientOptions, type GenericClient } from "static-shard";
import { schema, type Schema, type Records } from "./schema.js";

export interface Db {
  ${collectionKey}: Collection<Schema[${collectionIndex}], Records[${collectionIndex}]>;
}

const DEFAULT_BASE_PATH = ${JSON.stringify(opts.basePath)};

export function connect(opts?: Partial<ClientOptions>): Db {
  const generic: GenericClient<Schema, Records> = createClient<Schema, Records>(schema, {
    basePath: DEFAULT_BASE_PATH,
    ...opts,
  });
  return generic as unknown as Db;
}
`;
}
