import type { FieldSchemaEntry, Manifest } from "./types.js";

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * A valid TS type name from an arbitrary collection name: non-identifier chars (e.g. the hyphens in
 * a filename-derived `default-cards-2026`) become `_`, and a leading digit gets an `_` prefix.
 */
function typeNameFor(name: string): string {
  const safe = name.replace(/[^A-Za-z0-9_$]/g, "_").replace(/^([0-9])/, "_$1") || "_";
  return safe[0]!.toUpperCase() + safe.slice(1);
}

/** An object/interface key: emitted bare when it's a valid identifier, otherwise quoted (`"a-b": …`). */
function propKey(name: string): string {
  return IDENTIFIER_RE.test(name) ? name : JSON.stringify(name);
}

function tsTypeForKind(kind: string): string {
  switch (kind) {
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "string":
    case "date":
      return "string";
    case "json":
    default:
      return "unknown";
  }
}

/**
 * The distinct `tsImport` statements the emitted interface needs, in first-seen field order.
 * Deduplicated because several payload fields commonly draw their types from one module — emitting
 * the same import twice wouldn't compile.
 */
function payloadImportLines(fields: [string, FieldSchemaEntry][]): string {
  const seen = new Set<string>();
  for (const [, field] of fields) {
    if (field.tsType !== undefined && field.tsImport !== undefined) seen.add(field.tsImport);
  }
  return seen.size === 0 ? "" : `${[...seen].join("\n")}\n\n`;
}

function generatedHeader(generatorVersion: string): string {
  return `// generated by static-shard@${generatorVersion} — do not edit`;
}

export function generateSchemaTs(manifest: Manifest, generatorVersion: string): string {
  const { collection, fields } = manifest.schema;
  const typeName = typeNameFor(collection);
  const collectionKey = propKey(collection);
  const fieldEntries = Object.entries(fields);

  const interfaceLines = fieldEntries
    .map(([name, field]) => {
      // A configured `tsType` replaces the opaque `unknown` a payload field would otherwise get. It
      // is never validated against the data — the config asserts it, static-shard just relays it.
      const base = field.tsType ?? tsTypeForKind(field.kind);
      const tsType = field.multi ? `${base}[]` : base;
      // Payload-only "json" fields are opaque and their presence isn't tracked — always optional,
      // declared type or not: static-shard can't promise a key exists when it never checked.
      const optional = field.absent || field.kind === "json" ? "?" : "";
      return `  ${propKey(name)}${optional}: ${tsType};`;
    })
    .join("\n");

  const indexedFieldLines = fieldEntries
    .filter(([, field]) => field.indexed)
    .map(([name, field]) => {
      const operators = field.operators.map((op) => `"${op}"`).join(", ");
      const multi = field.multi ? ", multi: true" : "";
      const absent = field.absent ? ", absent: true" : "";
      const pk = field.pk ? ", pk: true" : "";
      // The runtime reads this tuple to narrow equals/in/some to the field's value union.
      const values = field.values ? `, values: [${field.values.map((v) => JSON.stringify(v)).join(", ")}]` : "";
      return `      ${propKey(name)}: { kind: "${field.kind}", operators: [${operators}]${multi}${absent}${pk}${values} },`;
    })
    .join("\n");

  const pkLine = manifest.schema.pk !== undefined ? `    pk: ${JSON.stringify(manifest.schema.pk)},\n` : "";

  /**
   * A named union per enum-like field, exported so app code can use it directly (a filter
   * component's prop, a dropdown's options) instead of hand-rolling the same literal union. The
   * record interface deliberately keeps these fields as plain `string` — see `tsTypeForKind`.
   */
  const valueUnions = fieldEntries
    .filter(([, field]) => field.indexed && field.values !== undefined)
    .map(([name, field]) => {
      const union = field.values!.map((v) => JSON.stringify(v)).join(" | ");
      return `export type ${typeName}${typeNameFor(name)} = ${union};`;
    })
    .join("\n");
  const valueUnionBlock = valueUnions ? `${valueUnions}\n\n` : "";

  return `${generatedHeader(generatorVersion)}
${payloadImportLines(fieldEntries)}${valueUnionBlock}export interface ${typeName} {
${interfaceLines}
}

export interface Records {
  ${collectionKey}: ${typeName};
}

export const schema = {
  ${collectionKey}: {
${pkLine}    fields: {
${indexedFieldLines}
    },
  },
} as const;

export type Schema = typeof schema;
`;
}

export function generateClientTs(
  manifest: Manifest,
  opts: { basePath: string; generatorVersion: string; manifestGzip?: boolean },
): string {
  const { collection } = manifest.schema;
  const collectionKey = propKey(collection);
  const collectionIndex = JSON.stringify(collection);

  return `${generatedHeader(opts.generatorVersion)}
import { createClient, type Collection, type ClientOptions, type GenericClient } from "static-shard";
import { schema, type Schema, type Records } from "./schema.js";

export interface Db {
  ${collectionKey}: Collection<Schema[${collectionIndex}], Records[${collectionIndex}]>;
}

const DEFAULT_BASE_PATH = ${JSON.stringify(opts.basePath)};
${
  opts.manifestGzip
    ? `// This build pre-compressed the manifest (\`gzip: true\`). Everything else the manifest points at
// carries \`.gz\` in its own path, but the manifest is fetched before any of that can be read — so the
// encoding is stamped here, by the same build that wrote the file.
const MANIFEST_GZIP = true;
`
    : ""
}
export function connect(opts?: Partial<ClientOptions>): Db {
  const generic: GenericClient<Schema, Records> = createClient<Schema, Records>(schema, {
    basePath: DEFAULT_BASE_PATH,
${opts.manifestGzip ? "    manifestGzip: MANIFEST_GZIP,\n" : ""}    ...opts,
  });
  return generic as unknown as Db;
}
`;
}
