// generated by blockdb@0.2.0 — do not edit
export type ProductsCategory = "Electronics" | "Fitness" | "Garden" | "Kitchen" | "Office" | "Outdoors" | "Stationery" | "Toys";

export interface Products {
  sku: string;
  name: string;
  category: string;
  price: number;
  inStock: boolean;
  discountPct?: number;
}

export interface Records {
  products: Products;
}

export const schema = {
  products: {
    pk: "sku",
    fields: {
      sku: { kind: "string", operators: ["equals", "in", "startsWith", "not"], pk: true },
      name: { kind: "string", operators: ["equals", "in", "startsWith", "not"] },
      category: { kind: "string", operators: ["equals", "in", "startsWith", "not"], values: ["Electronics", "Fitness", "Garden", "Kitchen", "Office", "Outdoors", "Stationery", "Toys"] },
      price: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not"] },
      inStock: { kind: "boolean", operators: ["equals", "not"] },
      discountPct: { kind: "number", operators: ["equals", "in", "gt", "gte", "lt", "lte", "not", "isAbsent", "exists"], absent: true },
    },
  },
} as const;

export type Schema = typeof schema;
